services:
  db:
    image: postgres:17
    container_name: nc-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3

  backend-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend-app
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CONFIG_LOCATION=classpath:/application-local.properties
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ENABLE_LIQUIBASE=true
    volumes:
      - /app
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: